"""Inline app/fx/arena_fx.js into the pages that use it (between the generated-code markers).

    python3 app/fx/build.py [extra.html ...]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
START, END = "/* ==== arena_fx.js (generated by app/fx/build.py) ==== */", "/* ==== end arena_fx.js ==== */"
PAGES = [os.path.join(HERE, "..", "play.html"), os.path.join(HERE, "..", "artifact_play.html")]


def build(paths):
    code = open(os.path.join(HERE, "arena_fx.js"), encoding="utf-8").read().strip()
    for path in paths:
        s = open(path, encoding="utf-8").read()
        i, j = s.find(START), s.find(END)
        if i < 0 or j < 0:
            sys.exit(f"{path}: markers not found")
        s = s[:i] + START + "\n" + code + "\n" + s[j:]
        open(path, "w", encoding="utf-8").write(s)
        print("built", os.path.relpath(path))


if __name__ == "__main__":
    build(PAGES + sys.argv[1:])
